### ISSUE TITLE
Mobile enterprise app store (AirWatch) service definition 

### ISSUE THREAD

**Issue by lukegonis** [bcgov/mobile-starter-kit#3]

**Comment by jleach** [comment]
@lukegonis @sheaphillips We don't do anything with AirWatch so I'm going to ax this ticket unless there are objections. All we do is provide Enterprise signing and then its up to the developer (or whoever signed the binary) to track down their ministry delegate who can upload it to the AirWatch store. 

The only reason we do it for a few projects is because I've helped on those projects and it was part of that role.

LMK.

**Comment by sheaphillips** [comment]
Service definition may not be the right thing, but we should make sure
somewhere in the mobile content to describe the role of AirWatch for mobile
developers and how to engage with them.

**Comment by jleach** [comment]
👍 I mentioned it as a foot note in the Service Definition and in the README that is the starting point of the larger corpus for mobile.
